name: 'Setup SWIG'
description: 'Download and install a version of SWIG'
author: 'mmomtchev'
inputs:
  version:
    description: 'Version to install'
    default: 'latest'
  branch:
    description: 'Branch to install'
    default: 'main'
  cache:
    description: 'Cache builds'
    default: true
  build:
    description: 'Build SWIG from source even if a binary distribution is available'
    default: false
  verbose:
    description: 'Verbose output'
    default: false
  token:
    description: 'Optional authentication token'
    default: ''
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'download'
  color: 'green'
