name: 'Setup SWIG'
description: 'Download and install a version of SWIG'
author: 'mmomtchev'
inputs:
  version:
    description: 'Version to install'
    default: 'latest'
  branch:
    description: 'Branch to install'
    default: 'main'
  cache:
    description: 'Cache builds'
    default: true
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'download'
  color: 'green'
