name: 'QA'
on:
  pull_request:
    branches: main
  push:
    branches: main


jobs:
  defaults:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        cache: [true, false]
    steps:
    - uses: mmomtchev/setup-swig@main
      with:
        cache: ${{ matrix.cache }}
        verbose: true

    - name: Verify
      run: swig -version


  version:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        cache: [true, false]
    steps:
    - uses: mmomtchev/setup-swig@main
      with:
        version: v4.1.0
        cache: ${{ matrix.cache }}
        verbose: true

    - name: Verify
      run: swig -version


  jse:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        cache: [true, false]
    steps:
    - uses: mmomtchev/setup-swig@main
      with:
        branch: jse
        cache: ${{ matrix.cache }}
        verbose: true

    - name: Verify
      run: swig-jse -version


  jse-main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        cache: [true, false]
    steps:
    - uses: mmomtchev/setup-swig@main
      with:
        branch: jse
        version: main
        cache: ${{ matrix.cache }}
        verbose: true

    - name: Verify
      run: swig-jse -version


  auth:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        cache: [true, false]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: mmomtchev/setup-swig@main
      with:
        branch: jse
        version: main
        cache: ${{ matrix.cache }}
        verbose: true
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Verify
      run: swig-jse -version
